"""Secure credential store (DESIGN-v2.md B2).

Two files, both gitignored, both OUT-OF-BAND from the password itself:

- `config/profiles.toml` — non-secret shape per profile: host, port,
  game_letter, handle, and optional ship_name/planet_name overrides. Safe
  to read/print/log; never holds a password.
- `config/secrets.json` — the ONLY on-disk home for passwords, created
  chmod 600 and re-asserted 600 on every write. Never imported into a
  log/transcript/history entry; the daemon's TranscriptLogger already has
  a redacted-send path (`log_redacted`) reused for every password send
  (see login.py) so a password never touches `logs/*.log` either.

Resolver precedence for `get_password()`: env var > secrets-file. This
lets a human/CI override or supply a password without ever writing it to
disk (e.g. a throwaway test profile), while the default persisted path is
the gitignored secrets file. `save_password()` always writes to the
secrets file (never to env — env is read-only/caller-managed) so a
NEW-registration password generated by the automaton is durably
recoverable exactly as DESIGN-v2 D9/the credential-mismatch incident requires.

**WO-MS-4:** `Profile.allow_register` is the opt-in policy gate for
automated NEW-character registration (default False, safe by omission —
every profile that predates this field is unaffected). Only an
`allow_register=true` profile may also omit `handle` in `profiles.toml`;
that shape exists for the name-bank rider (`twclient/name_bank.py`), which
draws a fresh handle/ship_name/planet_name per registration attempt
instead of pinning one. login.py's `char_create` dispatch is the actual
enforcement point — it raises before sending a single registration
keystroke if the profile hasn't opted in.

**TW-26 live-crawl driver:** `Profile.crawl_sacrificial` is a second,
independent opt-in gate (default False, mirroring `allow_register`'s
own shape exactly) — the code-enforced half of the crawler's A+C
protocol (a disposable, zero-asset character, plus a hub-supervisor able
to abort mid-crawl; see `twclient/crawl_driver.py`'s module docstring).
`crawl_driver.run_live_crawl()` refuses outright, before opening a
single connection, on any profile where this isn't `True`. A real
sacrificial-crawl profile is expected to set BOTH `crawl_sacrificial =
true` and `allow_register = true` — the pairing is a caller/config
convention, not enforced here; this field only gates the crawl half.

**§22/§23 Phase 1 (WO-P1) autonomous orchestrator / Autopilot (Trainer):**
`Profile.autonomous` is the backend fail-closed opt-in gate (default False)
that `twclient/autopilot.py`'s `AutopilotEngine` / `maybe_auto_start()`
hard-gate on before ANY autonomous send. Product UX names this
**Autopilot**; `profiles.toml` may set `autopilot = true` (preferred) or
the legacy synonym `autonomous = true`. `Profile.autopilot` is an alias
of `Profile.autonomous`. Every profile that predates this field, and every
profile that doesn't explicitly set it, keeps driving manually exactly as
before.
"""

import json
import os
import secrets as _secrets_mod
import stat
import string
import tomllib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = PROJECT_ROOT / "config"
PROFILES_PATH = CONFIG_DIR / "profiles.toml"
SECRETS_PATH = CONFIG_DIR / "secrets.json"

# Alnum-only, no punctuation: short enough and simple enough to survive
# the observed live TWGS "Passwords didn't match. Try again." flake
# (captured live across several live character registrations —
# tests/fixtures + this build's own session logs). The automaton always resends the exact same
# generated value for both the create and repeat-to-verify prompts (and
# any retry the server demands), so length/alphabet only matters for
# minimizing wire/echo mangling, not for match-consistency.
_PASSWORD_ALPHABET = string.ascii_letters + string.digits
_GENERATED_PASSWORD_LEN = 8


class CredentialError(Exception):
    """Profile/config problem — never raised for a merely-absent password
    (that's a legitimate None from get_password(), not an error)."""


# Last successfully parsed Profile per (profiles_path, name). Used when
# profiles.toml is mid-write/corrupt so long-lived clients (watch/spectate
# status polls, guardian reconnect) can keep serving the last-good shape
# instead of letting tomllib.TOMLDecodeError escape load_profile().
_profile_cache = {}


class Profile:
    def __init__(self, name, host, port, game_letter, handle=None, ship_name=None, planet_name=None, server=None,
                 allow_register=False, crawl_sacrificial=False, autonomous=False, autopilot=None):
        self.name = name
        self.host = host
        self.port = int(port)
        self.game_letter = game_letter
        self.handle = handle
        # WO-MS-4: whether the CALLER passed a concrete value for this
        # field, captured before any defaulting below -- the name-bank
        # rider (twclient/name_bank.py) needs to tell "explicitly set"
        # from "defaulted"/"blank" apart, which is otherwise lost the
        # instant this constructor fills a default in. A bare handle-less
        # profile (allow_register-only, no `handle` in profiles.toml) is
        # the new shape this enables; every existing profile still sets
        # handle explicitly, so this is a pure addition.
        self.handle_explicit = handle is not None
        self.ship_name_explicit = ship_name is not None
        self.planet_name_explicit = planet_name is not None
        self.ship_name = ship_name or (f"{handle}Ship" if handle else None)
        self.planet_name = planet_name or (f"{handle}World" if handle else None)
        self.server = server  # optional catalog key (WO-MS-1)
        # WO-MS-4: opt-in gate for automated NEW-character registration --
        # default False (safe by omission): every profile that predates
        # this field, and every profile that doesn't explicitly set it,
        # behaves exactly as before. See login.py's char_create dispatch.
        self.allow_register = bool(allow_register)
        # TW-26: opt-in gate for the live-crawl driver -- default False,
        # same safe-by-omission shape as allow_register above. See
        # twclient/crawl_driver.py's module docstring for the A+C
        # protocol this is the code-enforced half of.
        self.crawl_sacrificial = bool(crawl_sacrificial)
        # WO-P1 / tw2002-aiclient: trainer Autopilot gate. Product key is
        # `autopilot`; `autonomous` remains the backend attribute name.
        if autopilot is None:
            self.autonomous = bool(autonomous)
        else:
            self.autonomous = bool(autopilot)

    @property
    def autopilot(self):
        return self.autonomous

    @autopilot.setter
    def autopilot(self, value):
        self.autonomous = bool(value)

    def __repr__(self):
        return (
            f"Profile(name={self.name!r}, host={self.host!r}, port={self.port!r}, game_letter={self.game_letter!r}, "
            f"handle={self.handle!r}, server={self.server!r}, allow_register={self.allow_register!r}, "
            f"crawl_sacrificial={self.crawl_sacrificial!r}, autonomous={self.autonomous!r}, "
            f"autopilot={self.autopilot!r})"
        )


def _load_toml(path):
    if not path.exists():
        return {}
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        raise CredentialError(
            f"profiles_toml_parse_error:{path.name}:{e}"
        ) from e


def list_profiles(profiles_path=None):
    return sorted(_load_toml(profiles_path or PROFILES_PATH).keys())


def load_profile(name, profiles_path=None, servers_path=None):
    path = profiles_path or PROFILES_PATH
    cache_key = (str(path), name)
    try:
        data = _load_toml(path)
    except CredentialError as e:
        if str(e).startswith("profiles_toml_parse_error:"):
            cached = _profile_cache.get(cache_key)
            if cached is not None:
                return cached
        raise
    if name not in data:
        raise CredentialError(f"profile_not_found:{name}")
    p = data[name]
    server_key = p.get("server")
    host = p.get("host")
    port = p.get("port")
    if server_key and (host is None or port is None):
        from . import servers as servers_mod
        try:
            chost, cport = servers_mod.resolve_endpoint(server_key, path=servers_path)
        except servers_mod.ServerCatalogError as e:
            raise CredentialError(f"profile_server_unresolved:{name}:{e}") from e
        if host is None:
            host = chost
        if port is None:
            port = cport
    allow_register = bool(p.get("allow_register", False))
    crawl_sacrificial = bool(p.get("crawl_sacrificial", False))
    # Prefer product key `autopilot`; legacy `autonomous` remains valid.
    if "autopilot" in p:
        autonomous = bool(p.get("autopilot"))
    else:
        autonomous = bool(p.get("autonomous", False))
    required = ["game_letter"]
    # WO-MS-4: `handle` stays required for every profile as before UNLESS
    # it has explicitly opted into `allow_register` -- only THAT shape (a
    # profile that exists purely to auto-register a fresh character, e.g.
    # the name-bank rider in login.py/name_bank.py) may omit it. A normal
    # profile with no `allow_register` still fails loudly on a missing
    # handle exactly as before this change.
    if not allow_register and "handle" not in p:
        required.append("handle")
    missing = [k for k in required if k not in p]
    if host is None:
        missing.append("host")
    if port is None:
        missing.append("port")
    if missing:
        raise CredentialError(f"profile_incomplete:{name}:missing={missing}")
    profile = Profile(
        name=name,
        host=host,
        port=port,
        game_letter=p["game_letter"],
        handle=p.get("handle"),
        ship_name=p.get("ship_name"),
        planet_name=p.get("planet_name"),
        server=server_key,
        allow_register=allow_register,
        crawl_sacrificial=crawl_sacrificial,
        autonomous=autonomous,
    )
    _profile_cache[cache_key] = profile
    return profile


def _env_var_name(profile_name):
    safe = "".join(c if c.isalnum() else "_" for c in profile_name.upper())
    return f"TW2002_PASSWORD_{safe}"


def _read_secrets(secrets_path=None):
    path = secrets_path or SECRETS_PATH
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _write_secrets(data, secrets_path=None):
    path = secrets_path or SECRETS_PATH
    path.parent.mkdir(exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    fd = os.open(str(tmp_path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    os.chmod(tmp_path, 0o600)
    os.replace(str(tmp_path), str(path))
    os.chmod(path, 0o600)


def get_password(profile_name, secrets_path=None):
    """Resolver precedence: env > secrets-file. Returns None (not an
    error) when neither has a credential — that's the expected state for
    a profile that has never registered a character yet."""
    env_val = os.environ.get(_env_var_name(profile_name))
    if env_val:
        return env_val
    entry = _read_secrets(secrets_path).get(profile_name)
    if entry and entry.get("password"):
        return entry["password"]
    return None


def save_password(profile_name, password, secrets_path=None):
    """Persist a password to the gitignored, chmod-600 secrets file.
    Never touches the environment. Safe to call repeatedly (last write
    wins) — the automaton calls this once, eagerly, the moment it
    generates a NEW-registration password (see login.py), so the
    character is recoverable even if a later step in that same run
    fails."""
    path = secrets_path or SECRETS_PATH
    data = _read_secrets(path)
    data[profile_name] = {"password": password}
    _write_secrets(data, path)


def generate_password(length=_GENERATED_PASSWORD_LEN):
    """CSPRNG-generated (not `random`), alnum-only, short — see module
    docstring for why this survives the live match flake."""
    return "".join(_secrets_mod.choice(_PASSWORD_ALPHABET) for _ in range(length))


def secrets_file_mode_ok(secrets_path=None):
    """True if the secrets file doesn't exist yet, or exists at exactly
    chmod 600. Used by tests/ops checks — never auto-loosens permissions,
    only reports."""
    path = secrets_path or SECRETS_PATH
    if not path.exists():
        return True
    return stat.S_IMODE(os.stat(path).st_mode) == 0o600


def _toml_quote(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _format_toml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    return _toml_quote(value)


def _iter_toml_sections(text):
    """Yield (name|None, start, end) for each [section] and the preamble.

    `name` is None for the leading comment/preamble block before the first
    table. `end` is exclusive.
    """
    lines = text.splitlines(keepends=True)
    sections = []
    current_name = None
    current_start = 0
    offset = 0
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]") and not stripped.startswith("[["):
            inner = stripped[1:-1].strip()
            if current_start < offset or current_name is not None or offset == 0:
                sections.append((current_name, current_start, offset))
            current_name = inner
            current_start = offset
        offset += len(line)
    sections.append((current_name, current_start, len(text)))
    # Drop empty preamble if file starts with a section.
    if sections and sections[0][0] is None and sections[0][1] == sections[0][2]:
        sections = sections[1:]
    return sections


def _set_key_in_section_text(section_text, key, value):
    """Update or insert `key = value` inside one TOML table body (incl header)."""
    lines = section_text.splitlines(keepends=True)
    if not lines:
        return section_text
    key_re_prefix = f"{key} "
    key_re_eq = f"{key}="
    new_line = f"{key} = {_format_toml_value(value)}\n"
    out = [lines[0]]  # keep [name] header
    replaced = False
    for line in lines[1:]:
        stripped = line.lstrip()
        if stripped.startswith("#") or not stripped.strip():
            out.append(line)
            continue
        if stripped.startswith(key_re_prefix) or stripped.startswith(key_re_eq):
            # Preserve indentation if any.
            indent = line[: len(line) - len(line.lstrip())]
            ending = "\n" if line.endswith("\n") else ""
            out.append(f"{indent}{key} = {_format_toml_value(value)}{ending}")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        # Insert before trailing blank lines.
        insert_at = len(out)
        while insert_at > 1 and out[insert_at - 1].strip() == "":
            insert_at -= 1
        out.insert(insert_at, new_line if out[0].endswith("\n") or insert_at > 1 else new_line)
    body = "".join(out)
    if not body.endswith("\n"):
        body += "\n"
    return body


def set_profile_autopilot(name, enabled, profiles_path=None):
    """Persist Autopilot ON/OFF to profiles.toml (`autopilot =` key).

    Also clears a legacy `autonomous =` line in the same section when present
    so the product key is the sole source of truth after a write-back.
    """
    path = Path(profiles_path or PROFILES_PATH)
    if not path.exists():
        raise CredentialError(f"profiles_missing:{path}")
    text = path.read_text(encoding="utf-8")
    sections = _iter_toml_sections(text)
    found = False
    parts = []
    for sec_name, start, end in sections:
        chunk = text[start:end]
        if sec_name == name:
            found = True
            chunk = _set_key_in_section_text(chunk, "autopilot", bool(enabled))
            # Drop legacy synonym so load prefers the product key cleanly.
            chunk = _remove_key_from_section_text(chunk, "autonomous")
        parts.append(chunk)
    if not found:
        raise CredentialError(f"profile_not_found:{name}")
    new_text = "".join(parts)
    _atomic_write_text(path, new_text)
    # Bust cache for this profile.
    cache_key = (str(path), name)
    _profile_cache.pop(cache_key, None)


def _remove_key_from_section_text(section_text, key):
    lines = section_text.splitlines(keepends=True)
    if not lines:
        return section_text
    out = [lines[0]]
    for line in lines[1:]:
        stripped = line.lstrip()
        if stripped.startswith(f"{key} ") or stripped.startswith(f"{key}="):
            continue
        out.append(line)
    return "".join(out)


def _atomic_write_text(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(text, encoding="utf-8")
    os.replace(str(tmp_path), str(path))


def create_profile(
    name,
    *,
    game_letter,
    handle=None,
    server=None,
    host=None,
    port=None,
    ship_name=None,
    planet_name=None,
    allow_register=False,
    autopilot=False,
    profiles_path=None,
    servers_path=None,
):
    """Append a new profile section to profiles.toml. Raises if name exists."""
    path = Path(profiles_path or PROFILES_PATH)
    if not name or not str(name).strip():
        raise CredentialError("profile_name_required")
    name = str(name).strip()
    if any(c.isspace() for c in name) or name.startswith("["):
        raise CredentialError(f"profile_name_invalid:{name}")
    existing = _load_toml(path) if path.exists() else {}
    if name in existing:
        raise CredentialError(f"profile_exists:{name}")
    if not game_letter:
        raise CredentialError("profile_incomplete:missing=['game_letter']")
    if server is None and (host is None or port is None):
        raise CredentialError("profile_incomplete:missing=['server'|'host'+'port']")
    if not allow_register and not handle:
        raise CredentialError("profile_incomplete:missing=['handle']")

    fields = []
    if server:
        fields.append(("server", server))
    if host is not None:
        fields.append(("host", host))
    if port is not None:
        fields.append(("port", int(port)))
    fields.append(("game_letter", str(game_letter).upper()[:1]))
    if handle:
        fields.append(("handle", handle))
    if ship_name:
        fields.append(("ship_name", ship_name))
    if planet_name:
        fields.append(("planet_name", planet_name))
    if allow_register:
        fields.append(("allow_register", True))
    fields.append(("autopilot", bool(autopilot)))

    block_lines = [f"[{name}]"]
    for k, v in fields:
        block_lines.append(f"{k} = {_format_toml_value(v)}")
    block = "\n".join(block_lines) + "\n"

    if path.exists():
        text = path.read_text(encoding="utf-8")
        if text and not text.endswith("\n"):
            text += "\n"
        if text and not text.endswith("\n\n"):
            text += "\n"
        text = text + block
    else:
        text = block
    _atomic_write_text(path, text)
    return load_profile(name, profiles_path=path, servers_path=servers_path)


def list_profile_summaries(profiles_path=None, servers_path=None):
    """Rows for the tw2002-aiclient launcher: name, server display, game, autopilot."""
    path = profiles_path or PROFILES_PATH
    rows = []
    for name in list_profiles(profiles_path=path):
        try:
            profile = load_profile(name, profiles_path=path, servers_path=servers_path)
            server_display = profile.server or profile.host
            rows.append(
                {
                    "name": name,
                    "handle": profile.handle or "",
                    "server": server_display,
                    "game_letter": profile.game_letter,
                    "autopilot": bool(profile.autopilot),
                    "error": None,
                }
            )
        except CredentialError as e:
            rows.append(
                {
                    "name": name,
                    "handle": "",
                    "server": "?",
                    "game_letter": "?",
                    "autopilot": False,
                    "error": str(e),
                }
            )
    return rows
