"""Secure credential store (DESIGN-v2.md B2).

Two files, both gitignored, both OUT-OF-BAND from the password itself:

- `config/profiles.toml` — non-secret shape per profile: host, port,
  game_letter, handle, and optional ship_name/planet_name overrides. Safe
  to read/print/log; never holds a password.
- `config/secrets.json` — the ONLY on-disk home for passwords, created
  chmod 600 and re-asserted 600 on every write. Never imported into a
  log/transcript/history entry; the daemon's TranscriptLogger already has
  a redacted-send path (`log_redacted`) reused for every password send
  (see login.py) so a password never touches `logs/*.log` either.

Resolver precedence for `get_password()`: env var > secrets-file. This
lets a human/CI override or supply a password without ever writing it to
disk (e.g. a throwaway test profile), while the default persisted path is
the gitignored secrets file. `save_password()` always writes to the
secrets file (never to env — env is read-only/caller-managed) so a
NEW-registration password generated by the automaton is durably
recoverable exactly as DESIGN-v2 D9/the credential-mismatch incident requires.
"""

import json
import os
import secrets as _secrets_mod
import stat
import string
import tomllib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = PROJECT_ROOT / "config"
PROFILES_PATH = CONFIG_DIR / "profiles.toml"
SECRETS_PATH = CONFIG_DIR / "secrets.json"

# Alnum-only, no punctuation: short enough and simple enough to survive
# the observed live TWGS "Passwords didn't match. Try again." flake
# (captured live across several live character registrations —
# tests/fixtures + this build's own session logs). The automaton always resends the exact same
# generated value for both the create and repeat-to-verify prompts (and
# any retry the server demands), so length/alphabet only matters for
# minimizing wire/echo mangling, not for match-consistency.
_PASSWORD_ALPHABET = string.ascii_letters + string.digits
_GENERATED_PASSWORD_LEN = 8


class CredentialError(Exception):
    """Profile/config problem — never raised for a merely-absent password
    (that's a legitimate None from get_password(), not an error)."""


class Profile:
    def __init__(self, name, host, port, game_letter, handle, ship_name=None, planet_name=None):
        self.name = name
        self.host = host
        self.port = int(port)
        self.game_letter = game_letter
        self.handle = handle
        self.ship_name = ship_name or f"{handle}Ship"
        self.planet_name = planet_name or f"{handle}World"

    def __repr__(self):
        return f"Profile(name={self.name!r}, host={self.host!r}, port={self.port!r}, game_letter={self.game_letter!r}, handle={self.handle!r})"


def _load_toml(path):
    if not path.exists():
        return {}
    with open(path, "rb") as f:
        return tomllib.load(f)


def list_profiles(profiles_path=None):
    return sorted(_load_toml(profiles_path or PROFILES_PATH).keys())


def load_profile(name, profiles_path=None):
    data = _load_toml(profiles_path or PROFILES_PATH)
    if name not in data:
        raise CredentialError(f"profile_not_found:{name}")
    p = data[name]
    required = ("host", "port", "game_letter", "handle")
    missing = [k for k in required if k not in p]
    if missing:
        raise CredentialError(f"profile_incomplete:{name}:missing={missing}")
    return Profile(
        name=name,
        host=p["host"],
        port=p["port"],
        game_letter=p["game_letter"],
        handle=p["handle"],
        ship_name=p.get("ship_name"),
        planet_name=p.get("planet_name"),
    )


def _env_var_name(profile_name):
    safe = "".join(c if c.isalnum() else "_" for c in profile_name.upper())
    return f"TW2002_PASSWORD_{safe}"


def _read_secrets(secrets_path=None):
    path = secrets_path or SECRETS_PATH
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _write_secrets(data, secrets_path=None):
    path = secrets_path or SECRETS_PATH
    path.parent.mkdir(exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    fd = os.open(str(tmp_path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    os.chmod(tmp_path, 0o600)
    os.replace(str(tmp_path), str(path))
    os.chmod(path, 0o600)


def get_password(profile_name, secrets_path=None):
    """Resolver precedence: env > secrets-file. Returns None (not an
    error) when neither has a credential — that's the expected state for
    a profile that has never registered a character yet."""
    env_val = os.environ.get(_env_var_name(profile_name))
    if env_val:
        return env_val
    entry = _read_secrets(secrets_path).get(profile_name)
    if entry and entry.get("password"):
        return entry["password"]
    return None


def save_password(profile_name, password, secrets_path=None):
    """Persist a password to the gitignored, chmod-600 secrets file.
    Never touches the environment. Safe to call repeatedly (last write
    wins) — the automaton calls this once, eagerly, the moment it
    generates a NEW-registration password (see login.py), so the
    character is recoverable even if a later step in that same run
    fails."""
    path = secrets_path or SECRETS_PATH
    data = _read_secrets(path)
    data[profile_name] = {"password": password}
    _write_secrets(data, path)


def generate_password(length=_GENERATED_PASSWORD_LEN):
    """CSPRNG-generated (not `random`), alnum-only, short — see module
    docstring for why this survives the live match flake."""
    return "".join(_secrets_mod.choice(_PASSWORD_ALPHABET) for _ in range(length))


def secrets_file_mode_ok(secrets_path=None):
    """True if the secrets file doesn't exist yet, or exists at exactly
    chmod 600. Used by tests/ops checks — never auto-loosens permissions,
    only reports."""
    path = secrets_path or SECRETS_PATH
    if not path.exists():
        return True
    return stat.S_IMODE(os.stat(path).st_mode) == 0o600
